
export const ENEMY_DATA : Array<{
    delay: number, 
    y: number, 
    speed: number, 
    direction: number}> = [
        {
            delay:5,
            y:100,
            speed:0.8,
            direction:1
        },
        {
            delay:20,
            y:250,
            speed:1,
            direction:1
        },
        {
            delay:40,
            y:200,
            speed:0.6,
            direction:-1
        },
        {
            delay:45,
            y:400,
            speed:1.2,
            direction:1
        },        {
            delay:50,
            y:60,
            speed:0.7,
            direction:1
        },
        {
            delay:60,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:70,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:75,
            y:100,
            speed:0.5,
            direction:1
        },
        {
            delay:80,
            y:10,
            speed:1,
            direction:-1
        },
        {
            delay:85,
            y:400,
            speed:0.4,
            direction:1
        },      {
            delay:90,
            y:330,
            speed:0.8,
            direction:1
        },
        {
            delay:95,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:100,
            y:180,
            speed:1.2,
            direction:1
        },
        {
            delay:105,
            y:-45,
            speed:0.2,
            direction:1
        },
        {
            delay:110,
            y:150,
            speed:1.2,
            direction:-1
        },
        {
            delay:120,
            y:250,
            speed:1,
            direction:1
        },
        {
            delay:122,
            y:200,
            speed:0.6,
            direction:-1
        },
        {
            delay:130,
            y:400,
            speed:1.2,
            direction:1
        },        {
            delay:150,
            y:60,
            speed:0.7,
            direction:1
        },
        {
            delay:135,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:137,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:140,
            y:100,
            speed:0.5,
            direction:1
        },
        {
            delay:140,
            y:10,
            speed:1,
            direction:-1
        },
        {
            delay:145,
            y:400,
            speed:0.4,
            direction:1
        },
        {
            delay:149,
            y:300,
            speed:0.8,
            direction:-1
        },
        {
            delay:153,
            y:250,
            speed:1,
            direction:1
        },
        {
            delay:157,
            y:200,
            speed:0.6,
            direction:-1
        },
        {
            delay:161,
            y:380,
            speed:1.2,
            direction:1
        },        {
            delay:165,
            y:0,
            speed:0.7,
            direction:1
        },
        {
            delay:169,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:175,
            y:400,
            speed:1,
            direction:-1
        },
        {
            delay:179,
            y:100,
            speed:0.5,
            direction:1
        },
        {
            delay:183,
            y:10,
            speed:1,
            direction:-1
        },
        {
            delay:187,
            y:380,
            speed:0.4,
            direction:1
        },      {
            delay:191,
            y:200,
            speed:0.8,
            direction:1
        },
        {
            delay:195,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:199,
            y:-30,
            speed:1.2,
            direction:1
        },
        {
            delay:203,
            y:10,
            speed:0.2,
            direction:1
        },
        {
            delay:207,
            y:150,
            speed:1.2,
            direction:-1
        },
        {
            delay:211,
            y:250,
            speed:1,
            direction:1
        },
        {
            delay:215,
            y:200,
            speed:0.6,
            direction:-1
        },
        {
            delay:219,
            y:-45,
            speed:1.2,
            direction:1
        },        {
            delay:223,
            y:60,
            speed:0.7,
            direction:-1
        },
        {
            delay:227,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:231,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:235,
            y:400,
            speed:0.5,
            direction:1
        },
        {
            delay:239,
            y:10,
            speed:1,
            direction:-1
        },
        {
            delay:243,
            y:350,
            speed:0.4,
            direction:1
        },
        {
            delay:245,
            y:100,
            speed:0.8,
            direction:1
        },
        {
            delay:249,
            y:200,
            speed:0.6,
            direction:-1
        },
        {
            delay:251,
            y:0,
            speed:1.2,
            direction:1
        },        {
            delay:253,
            y:60,
            speed:0.7,
            direction:1
        },
        {
            delay:255,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:257,
            y:-45,
            speed:1,
            direction:-1
        },
        {
            delay:259,
            y:100,
            speed:0.5,
            direction:1
        },
        {
            delay:261,
            y:10,
            speed:1,
            direction:-1
        },
        {
            delay:263,
            y:400,
            speed:0.4,
            direction:-1
        },      {
            delay:265,
            y:300,
            speed:0.8,
            direction:1
        },
        {
            delay:267,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:269,
            y:0,
            speed:0.2,
            direction:-1
        },
        {
            delay:271,
            y:100,
            speed:0.2,
            direction:1
        },
        {
            delay:273,
            y:150,
            speed:1.2,
            direction:-1
        },
        {
            delay:275,
            y:250,
            speed:1,
            direction:-1
        },
        {
            delay:277,
            y:200,
            speed:0.6,
            direction:-1
        },
        {
            delay:279,
            y:0,
            speed:1.2,
            direction:1
        },        {
            delay:281,
            y:60,
            speed:0.7,
            direction:1
        },
        {
            delay:283,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:285,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:287,
            y:-45,
            speed:0.5,
            direction:1
        },
        {
            delay:289,
            y:150,
            speed:1,
            direction:-1
        },
        {
            delay:291,
            y:400,
            speed:1.4,
            direction:1
        },
        {
            delay:293,
            y:100,
            speed:0.8,
            direction:-1
        },
        {
            delay:295,
            y:250,
            speed:0.5,
            direction:1
        },
        {
            delay:297,
            y:200,
            speed:0.6,
            direction:-1
        },
        {
            delay:299,
            y:380,
            speed:1.2,
            direction:1
        },        {
            delay:301,
            y:-45,
            speed:0.7,
            direction:1
        },
        {
            delay:303,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:305,
            y:400,
            speed:1,
            direction:-1
        },
        {
            delay:307,
            y:100,
            speed:0.5,
            direction:1
        },
        {
            delay:309,
            y:10,
            speed:1,
            direction:-1
        },
        {
            delay:311,
            y:380,
            speed:0.4,
            direction:1
        },      {
            delay:313,
            y:0,
            speed:0.8,
            direction:-1
        },
        {
            delay:315,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:317,
            y:400,
            speed:1.2,
            direction:1
        },
        {
            delay:319,
            y:10,
            speed:0.2,
            direction:1
        },
        {
            delay:321,
            y:150,
            speed:1.2,
            direction:-1
        },
        {
            delay:325,
            y:-45,
            speed:0.6,
            direction:-1
        },
        {
            delay:327,
            y:400,
            speed:1.2,
            direction:1
        },        {
            delay:329,
            y:60,
            speed:0.7,
            direction:-1
        },
        {
            delay:331,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:333,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:335,
            y:0,
            speed:0.5,
            direction:1
        },
        {
            delay:337,
            y:10,
            speed:1,
            direction:-1
        },
        {
            delay:339,
            y:350,
            speed:0.4,
            direction:1
        },
        {
            delay:340,
            y:100,
            speed:0.8,
            direction:1
        },
        {
            delay:341,
            y:250,
            speed:0.2,
            direction:1
        },
        {
            delay:342,
            y:200,
            speed:0.6,
            direction:-1
        },
        {
            delay:343,
            y:400,
            speed:1.4,
            direction:-1
        },        {
            delay:344,
            y:60,
            speed:0.7,
            direction:1
        },
        {
            delay:345,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:346,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:348,
            y:10,
            speed:1,
            direction:-1
        },
        {
            delay:349,
            y:400,
            speed:0.4,
            direction:1
        },      {
            delay:350,
            y:330,
            speed:0.8,
            direction:1
        },
        {
            delay:351,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:352,
            y:180,
            speed:1.2,
            direction:1
        },
        {
            delay:353,
            y:-45,
            speed:0.2,
            direction:1
        },
        {
            delay:354,
            y:150,
            speed:1.2,
            direction:-1
        },
        {
            delay:357,
            y:400,
            speed:1.2,
            direction:1
        },        {
            delay:358,
            y:60,
            speed:0.7,
            direction:1
        },
        {
            delay:359,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:360,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:361,
            y:100,
            speed:0.5,
            direction:1
        },
        {
            delay:362,
            y:10,
            speed:1,
            direction:-1
        },
        {
            delay:363,
            y:400,
            speed:0.4,
            direction:1
        },
        {
            delay:364,
            y:300,
            speed:0.8,
            direction:-1
        },
        {
            delay:365,
            y:250,
            speed:0.4,
            direction:1
        },
        {
            delay:366,
            y:200,
            speed:0.6,
            direction:-1
        },
        {
            delay:367,
            y:380,
            speed:1.2,
            direction:1
        },
        {
            delay:369,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:370,
            y:400,
            speed:1,
            direction:-1
        },
        {
            delay:371,
            y:100,
            speed:0.5,
            direction:1
        },
        {
            delay:372,
            y:10,
            speed:1,
            direction:-1
        },
        {
            delay:373,
            y:380,
            speed:0.4,
            direction:1
        },      {
            delay:374,
            y:200,
            speed:0.8,
            direction:1
        },
        {
            delay:376,
            y:-30,
            speed:1.2,
            direction:1
        },
        {
            delay:377,
            y:10,
            speed:0.2,
            direction:1
        },
        {
            delay:378,
            y:150,
            speed:1.2,
            direction:-1
        },
        {
            delay:379,
            y:250,
            speed:1.2,
            direction:-1
        },
        {
            delay:380,
            y:200,
            speed:0.6,
            direction:-1
        },
        {
            delay:381,
            y:-45,
            speed:0.2,
            direction:1
        },        {
            delay:382,
            y:60,
            speed:0.7,
            direction:-1
        },
        {
            delay:383,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:384,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:385,
            y:400,
            speed:0.5,
            direction:1
        },
        {
            delay:387,
            y:350,
            speed:0.4,
            direction:1
        },
        {
            delay:389,
            y:100,
            speed:0.8,
            direction:1
        },
        {
            delay:391,
            y:200,
            speed:0.6,
            direction:-1
        },
        {
            delay:392,
            y:0,
            speed:1.2,
            direction:1
        },        {
            delay:393,
            y:60,
            speed:0.7,
            direction:1
        },
        {
            delay:394,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:395,
            y:-45,
            speed:1,
            direction:-1
        },
        {
            delay:396,
            y:100,
            speed:0.5,
            direction:1
        },
        {
            delay:397,
            y:10,
            speed:1,
            direction:-1
        },
        {
            delay:398,
            y:400,
            speed:0.4,
            direction:-1
        },      {
            delay:399,
            y:300,
            speed:0.8,
            direction:1
        },
        {
            delay:400,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:402,
            y:100,
            speed:0.2,
            direction:1
        },
        {
            delay:403,
            y:150,
            speed:1.2,
            direction:-1
        },
        {
            delay:404,
            y:250,
            speed:0.4,
            direction:1
        },
        {
            delay:405,
            y:200,
            speed:0.6,
            direction:-1
        },
        {
            delay:406,
            y:0,
            speed:1.2,
            direction:1
        },        {
            delay:407,
            y:60,
            speed:0.7,
            direction:1
        },
        {
            delay:408,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:409,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:410,
            y:-45,
            speed:0.5,
            direction:1
        },
        {
            delay:411,
            y:150,
            speed:1,
            direction:-1
        },
        {
            delay:412,
            y:400,
            speed:0.4,
            direction:1
        },
        {
            delay:413,
            y:100,
            speed:0.8,
            direction:-1
        },
        {
            delay:415,
            y:200,
            speed:0.6,
            direction:-1
        },
        {
            delay:416,
            y:380,
            speed:1.2,
            direction:1
        },        {
            delay:417,
            y:-45,
            speed:0.7,
            direction:1
        },
        {
            delay:418,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:419,
            y:400,
            speed:1,
            direction:-1
        },
        {
            delay:420,
            y:100,
            speed:0.5,
            direction:1
        },
        {
            delay:421,
            y:10,
            speed:1,
            direction:-1
        },
        {
            delay:422,
            y:380,
            speed:0.4,
            direction:1
        },      {
            delay:423,
            y:0,
            speed:0.8,
            direction:-1
        },
        {
            delay:424,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:425,
            y:400,
            speed:1.2,
            direction:1
        },
        {
            delay:427,
            y:150,
            speed:1.2,
            direction:-1
        },
        {
            delay:428,
            y:250,
            speed:1,
            direction:1
        },
        {
            delay:429,
            y:-45,
            speed:0.6,
            direction:-1
        },
        {
            delay:430,
            y:400,
            speed:1.2,
            direction:1
        },        {
            delay:431,
            y:60,
            speed:0.7,
            direction:-1
        },
        {
            delay:432,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:433,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:434,
            y:0,
            speed:0.5,
            direction:1
        },
        {
            delay:435,
            y:10,
            speed:1,
            direction:-1
        },
        {
            delay:436,
            y:350,
            speed:0.4,
            direction:1
        },
        {
            delay:437,
            y:100,
            speed:0.8,
            direction:1
        },
        {
            delay:438,
            y:250,
            speed:0.2,
            direction:1
        },
        {
            delay:439,
            y:200,
            speed:0.6,
            direction:-1
        },
        {
            delay:441,
            y:400,
            speed:1.4,
            direction:-1
        },        {
            delay:443,
            y:60,
            speed:0.7,
            direction:1
        },
        {
            delay:444,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:446,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:448,
            y:10,
            speed:1,
            direction:-1
        },
        {
            delay:450,
            y:400,
            speed:0.4,
            direction:1
        },      {
            delay:451,
            y:330,
            speed:0.8,
            direction:1
        },
        {
            delay:452,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:454,
            y:180,
            speed:1.2,
            direction:1
        },
        {
            delay:455,
            y:-45,
            speed:0.2,
            direction:1
        },
        {
            delay:456,
            y:150,
            speed:1.2,
            direction:-1
        },
        {
            delay:458,
            y:400,
            speed:1.2,
            direction:1
        },        {
            delay:459,
            y:60,
            speed:0.7,
            direction:1
        },
        {
            delay:461,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:462,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:464,
            y:100,
            speed:0.5,
            direction:1
        },
        {
            delay:465,
            y:10,
            speed:1,
            direction:-1
        },
        {
            delay:466,
            y:400,
            speed:0.4,
            direction:1
        },
        {
            delay:467,
            y:300,
            speed:0.8,
            direction:-1
        },
        {
            delay:469,
            y:250,
            speed:0.4,
            direction:1
        },
        {
            delay:471,
            y:200,
            speed:0.6,
            direction:-1
        },
        {
            delay:472,
            y:380,
            speed:1.2,
            direction:1
        },
        {
            delay:473,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:475,
            y:400,
            speed:1,
            direction:-1
        },
        {
            delay:476,
            y:100,
            speed:0.5,
            direction:1
        },
        {
            delay:477,
            y:10,
            speed:1,
            direction:-1
        },
        {
            delay:479,
            y:380,
            speed:0.4,
            direction:1
        },      {
            delay:480,
            y:200,
            speed:0.8,
            direction:1
        },
        {
            delay:481,
            y:-30,
            speed:1.2,
            direction:1
        },
        {
            delay:482,
            y:10,
            speed:0.2,
            direction:1
        },
        {
            delay:484,
            y:150,
            speed:1.2,
            direction:-1
        },
        {
            delay:486,
            y:250,
            speed:1.2,
            direction:-1
        },
        {
            delay:487,
            y:200,
            speed:0.6,
            direction:-1
        },
        {
            delay:488,
            y:-45,
            speed:0.2,
            direction:1
        },        {
            delay:489,
            y:60,
            speed:0.7,
            direction:-1
        },
        {
            delay:491,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:493,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:495,
            y:400,
            speed:0.5,
            direction:1
        },
        {
            delay:496,
            y:350,
            speed:0.4,
            direction:1
        },
        {
            delay:497,
            y:100,
            speed:0.8,
            direction:1
        },
        {
            delay:498,
            y:200,
            speed:0.6,
            direction:-1
        },
        {
            delay:500,
            y:0,
            speed:1.2,
            direction:1
        },        {
            delay:501,
            y:60,
            speed:0.7,
            direction:1
        },
        {
            delay:503,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:504,
            y:-45,
            speed:1,
            direction:-1
        },
        {
            delay:505,
            y:100,
            speed:0.5,
            direction:1
        },
        {
            delay:507,
            y:10,
            speed:1,
            direction:-1
        },
        {
            delay:508,
            y:400,
            speed:0.4,
            direction:-1
        },      {
            delay:399,
            y:300,
            speed:0.8,
            direction:1
        },
        {
            delay:509,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:511,
            y:100,
            speed:0.2,
            direction:1
        },
        {
            delay:513,
            y:150,
            speed:1.2,
            direction:-1
        },
        {
            delay:514,
            y:250,
            speed:0.4,
            direction:1
        },
        {
            delay:515,
            y:200,
            speed:0.6,
            direction:-1
        },
        {
            delay:517,
            y:0,
            speed:1.2,
            direction:1
        },        {
            delay:518,
            y:60,
            speed:0.7,
            direction:1
        },
        {
            delay:519,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:520,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:522,
            y:-45,
            speed:0.5,
            direction:1
        },
        {
            delay:523,
            y:150,
            speed:1,
            direction:-1
        },
        {
            delay:524,
            y:400,
            speed:0.4,
            direction:1
        },
        {
            delay:525,
            y:100,
            speed:0.8,
            direction:-1
        },
        {
            delay:526,
            y:200,
            speed:0.6,
            direction:-1
        },
        {
            delay:527,
            y:380,
            speed:1.2,
            direction:1
        },        {
            delay:529,
            y:-45,
            speed:0.7,
            direction:1
        },
        {
            delay:530,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:531,
            y:400,
            speed:1,
            direction:-1
        },
        {
            delay:532,
            y:100,
            speed:0.5,
            direction:1
        },
        {
            delay:533,
            y:10,
            speed:1,
            direction:-1
        },
        {
            delay:535,
            y:380,
            speed:0.4,
            direction:1
        },      {
            delay:536,
            y:0,
            speed:0.8,
            direction:-1
        },
        {
            delay:537,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:538,
            y:400,
            speed:1.2,
            direction:1
        },
        {
            delay:540,
            y:150,
            speed:1.2,
            direction:-1
        },
        {
            delay:541,
            y:250,
            speed:1,
            direction:1
        },
        {
            delay:542,
            y:-45,
            speed:0.6,
            direction:-1
        },
        {
            delay:543,
            y:400,
            speed:1.2,
            direction:1
        },        {
            delay:545,
            y:60,
            speed:0.7,
            direction:-1
        },
        {
            delay:546,
            y:120,
            speed:1,
            direction:1
        },
        {
            delay:548,
            y:280,
            speed:1,
            direction:-1
        },
        {
            delay:549,
            y:0,
            speed:0.5,
            direction:1
        },
        {
            delay:550,
            y:10,
            speed:1,
            direction:-1
        },
        {
            delay:551,
            y:350,
            speed:0.4,
            direction:1
        }

    ]

